apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-fagsystem-mock
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8080
  ingresses:
{{#each ingresses}}
    - "{{this}}"
{{/each}}
  liveness:
    path: /sosialhjelp/fagsystem-mock/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/fagsystem-mock/isAlive
    initialDelay: 20
    timeout: 1
  accessPolicy:
    outbound:
      external:
        - host: "digisos.labs.nais.io"
      rules:
        - application: digisos
  prometheus:
    enabled: {{prometheusEnabled}}
    path: /actuator/metrics
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 1m
      memory: 64Mi
  env:
    - name: APPRES_CMS_URL
      value: {{appresCmsUrl}}
