apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-fagsystem-mock
  namespace: {{namespace}}
  labels:
    team: digisos
spec:
  image: docker.pkg.github.com/navikt/sosialhjelp-woldena-tm/sosialhjelp-woldena-tm:{{version}}
  port: 8080
  ingresses:
{{#each ingresses}}
    - "{{this}}"
{{/each}}
  liveness:
    path: /sosialhjelp/fagsystem-mock/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/fagsystem-mock/internal/isAlive
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /actuator/metrics
  replicas:
    min: 1
    max: 4
  ingresses: {{ingresses}}
  webproxy: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    - name: APPRES_CMS_URL
      value: {{appresCmsUrl}}
