packages:
  - '.'
allowBuilds:
  sharp: false
  unrs-resolver: false
minimumReleaseAge: 2880
overrides:
  postcss@<8.5.10: ^8.5.10
  react-day-picker: 9.13.2
  sharp@<0.35.0: ^0.35.4
  browserslist@<4.28.7: ^4.28.9
