version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: GitHub package registry login
          command: |
            echo "$DOCKER_PASSWORD_GITHUB" | docker login -u "$DOCKER_USERNAME_GITHUB" --password-stdin docker.pkg.github.com
      - run:
          name: Checkout CI scripts
          command: |
            git clone https://github.com/navikt/github-apps-support.git
            git clone https://github.com/navikt/sosialhjelp-ci.git
            echo "export PATH=\"`pwd`/github-apps-support/bin:`pwd`/sosialhjelp-ci/bin:$PATH\"" >> $BASH_ENV
      - run:
          name: Generate version number and docker image tags
          command: |
            VERSION=$(create-artifact-version.sh)
            echo "export DOCKER_TAG=\"docker.pkg.github.com/navikt/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PROJECT_REPONAME:$VERSION\"" >> $BASH_ENV
      - run:
          name: Build docker image
          command: docker build -t $DOCKER_TAG . || true # FIXME: Remove || true later
      - run:
          name: Create tag and release
          command: |
            echo $DIGISOS_KEY | tr '_' '\n' > digisos.key
            GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh digisos.key $DIGISOS_APPID`)
            rm digisos.key

            create-github-release.sh -p $CIRCLE_PROJECT_REPONAME -t $(create-artifact-version.sh) \
            -c $CIRCLE_SHA1 -m "$(format-commit-message.sh)" -a $GH_TOKEN
      - run:
          name: Docker push
          command: |
            echo $DOCKER_TAG
            docker push $DOCKER_TAG

  deploy_miljo:
    docker:
      - image: navikt/deployment-cli:v0.2.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy versjon=${VERSION} til miljø=${MILJO} i dev-sbs
          command: |
            deployment-cli deploy create --cluster=dev-sbs --repository=navikt/sosialhjelp-fagsystem-mock --team=digisos -r=nais.yaml --var version=${VERSION} --vars=nais/dev/${MILJO}.json

  deploy_prod:
    docker:
      - image: navikt/deployment-cli:v0.2.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy versjon=${VERSION} til prod
          command: |
            deployment-cli deploy create --cluster=prod-sbs --repository=navikt/sosialhjelp-fagsystem-mock --team=digisos -r=nais.yaml --var version=${VERSION} --vars=nais/prod/default.json

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
#      - deploy_dev:
#          requires:
#            - release
#          filters:
#            branches:
#              only: master