/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Feltet "type" angir hvilken type hendelse det er. Se egen definisjon per hendelse. Det som er dokumentert direkte under er kun det som er felles for alle hendelser.
 */
export type Hendelse =
  | NyttNAVKontorBehandlerSoknaden
  | NyStatusPaSoknaden
  | EtVedtakITilknytningTilSoknadenHarBlittFattet
  | VeilederBerOmMerDokumentasjonFraSoker
  | ForelopigSvar
  | EnSakITilknytningTilSoknadenHarBlittOpprettetOgHarStatus
  | Utbetaling
  | Vilkar
  | Rammevedtak;
export type NyttNAVKontorBehandlerSoknaden = {
  type?: "tildeltNavKontor";
  [k: string]: any;
};
export type NyStatusPaSoknaden = {
  type?: "soknadsStatus";
  [k: string]: any;
};
/**
 * Det er kun vedtak som ligger inn under Sosialtjenesteloven som skal sendes.
 */
export type EtVedtakITilknytningTilSoknadenHarBlittFattet = {
  type?: "vedtakFattet";
  [k: string]: any;
};
export type VeilederBerOmMerDokumentasjonFraSoker = {
  type?: "dokumentasjonEtterspurt";
  [k: string]: any;
};
export type ForelopigSvar = {
  type?: "forelopigSvar";
  [k: string]: any;
};
/**
 * Status på sak som vil resultere i et vedtak.
 */
export type EnSakITilknytningTilSoknadenHarBlittOpprettetOgHarStatus = {
  type?: "saksStatus";
  [k: string]: any;
};
/**
 * Utbetalingsinformasjon
 */
export type Utbetaling = {
  type?: "utbetaling";
  [k: string]: any;
};
/**
 * Vilkar
 */
export type Vilkar = {
  type?: "vilkar";
  [k: string]: any;
};
/**
 * Rammevedtak
 */
export type Rammevedtak = {
  type?: "rammevedtak";
  [k: string]: any;
};
