name: Build and deploy to dev
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          registry-url: "https://npm.pkg.github.com"
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Build application
        run: npm run build
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: teamdigisos
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          tag: latest
      - name: Deploy til dev
        uses: nais/deploy/actions/deploy@v2
        env:
          RESOURCE: nais.yaml
          CLUSTER: dev-gcp
          VARS: nais/dev/mock.json
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
          VAR: image=${{ needs.build.outputs.image }}
