name: Build and deploy to dev

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
          registry-url: "https://npm.pkg.github.com"
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Build application
        run: npm run build
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: teamdigisos
          tag: latest

  deploy:
    name: Deploy til dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Deploy
        uses: nais/deploy/actions/deploy@v2
        env:
          RESOURCE: nais.yaml
          CLUSTER: dev-gcp
          VARS: nais/dev/mock.json
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
          VAR: image=${{ needs.build.outputs.image }}
