name: Deploy Dev
on:
  repository_dispatch:
    types: [deploy_miljo_tag]

jobs:
  deploy:
    name: Deploy to dev-sbs
    runs-on: ubuntu-latest
    if: github.event.action == 'deploy_miljo_tag'
    steps:
      - name: Sett env variabler
        run: |
          PROJECT_NAME=$(echo ${{ github.repository }} | cut -d/ -f2)
          echo "IMAGE=docker.pkg.github.com/${{ github.repository }}/$PROJECT_NAME:${{ github.event.client_payload.TAG }}" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.TAG }}

      - name: Deploy til dev-sbs
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais.yaml
          CLUSTER: dev-sbs
          VARS: nais/dev/${{ github.event.client_payload.MILJO }}.json
          REF: ${{ github.event.client_payload.TAG }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ env.IMAGE }}
