name: Deploy til dev
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Deploy til dev
        uses: nais/deploy/actions/deploy@v2
        env:
          RESOURCE: nais.yaml
          CLUSTER: dev-gcp
          VARS: nais/dev/mock.json
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
          VAR: image=europe-north1-docker.pkg.dev/nais-management-233d/teamdigisos/sosialhjelp-fagsystem-mock-mock:latest
