name: Deploy Dev
on:
    repository_dispatch:
        types: [deploy_miljo_tag]

jobs:
    deploy:
        name: Deploy to dev-sbs
        runs-on: ubuntu-latest
        if: github.event.action == 'deploy_miljo_tag'
        container: navikt/deployment-cli:0.4.0
        steps:
            - name: Will be deployed to q0?
              if: github.event.client_payload.MILJO == 'q0'
              run: |
                echo $(jq -r '.client_payload.TAG' $GITHUB_EVENT_PATH)
                echo ${{ github.sha }}
                echo ${{ github.ref }}
                echo ${{ github.head_ref }}
                echo ${{ github.base_ref }}
                echo ${{ github.actor }}

            - name: Will be deployed to q0?
              if: github.event.client_payload.MILJO == 'q1'
              run: |
                echo test 2
            - uses: actions/checkout@v1
              with:
                  refs: test
            - name: Deploy to dev $(jq -r '.client_payload.MILJO' $GITHUB_EVENT_PATH)
              run: |
                  MILJO=$(jq -r '.client_payload.MILJO' $GITHUB_EVENT_PATH)
                  TAG=$(jq -r '.client_payload.TAG' $GITHUB_EVENT_PATH)
                  git checkout ${TAG}
                  deployment-cli deploy create --cluster=dev-sbs --repository=${GITHUB_REPOSITORY} --team=teamdigisos -r=nais.yaml --var version=${TAG} --vars=nais/dev/${MILJO}.json
              env:
                  DEPLOYMENT_USERNAME: ${{ secrets.DEPLOYMENT_USERNAME }}
                  DEPLOYMENT_PASSWORD: ${{ secrets.DEPLOYMENT_PASSWORD }}
