name: Deploy Dev
on:
    repository_dispatch:
        types: [deploy_miljo_tag]

jobs:
    deploy:
        name: Deploy to dev-sbs
        runs-on: ubuntu-latest
        if: github.event.action == 'deploy_miljo_tag'
        container: navikt/deployment-cli:0.4.0
        steps:
            - name: Will be deployed to q0?
              if: github.event.client_payload.MILJO == 'q0'
              run: |
                echo ~~Informasjon~~
                echo author: ${{ github.actor }}
                echo tag:  ${{github.event.client_payload.TAG}}
                echo miljo: ${{github.event.client_payload.MILJO}}
            - name: Will be deployed to q1?
              if: github.event.client_payload.MILJO == 'q1'
              run: |
                echo ~~Informasjon~~
                echo author: ${{ github.actor }}
                echo tag:  ${{github.event.client_payload.TAG}}
                echo miljo: ${{github.event.client_payload.MILJO}}
            - uses: actions/checkout@v1
            - name: Deploy to dev
              run: |
                  MILJO=$(jq -r '.client_payload.MILJO' $GITHUB_EVENT_PATH)
                  TAG=$(jq -r '.client_payload.TAG' $GITHUB_EVENT_PATH)
                  git checkout ${TAG}
                  deployment-cli deploy create --cluster=dev-sbs --repository=${GITHUB_REPOSITORY} --team=teamdigisos -r=nais.yaml --var version=${TAG} --vars=nais/dev/${MILJO}.json
              env:
                  DEPLOYMENT_USERNAME: ${{ secrets.DEPLOYMENT_USERNAME }}
                  DEPLOYMENT_PASSWORD: ${{ secrets.DEPLOYMENT_PASSWORD }}
