name: Deploy
on: repository_dispatch

jobs:
  deploy:
    name: Deploy to environment
    runs-on: ubuntu-latest
    container: navikt/deployment-cli:0.4.0
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to environment
        shell: bash
        run: |
          IFS=- read MILJO VERSION <<< $(jq -r '.action' $GITHUB_EVENT_PATH)

          echo "Checkout version $VERSION"
          git checkout $VERSION

          if [[ $MILJO == "q0" || $MILJO == "q1" ]]; then
            echo "Deploy $VERSION to $MILJO in dev-sbs"
            deployment-cli deploy create --cluster=dev-sbs --repository=${GITHUB_REPOSITORY} --team=digisos -r=nais.yaml --var version=${VERSION} --vars=nais/dev/${MILJO}.json
          elif [[ $MILJO == "p" ]]; then
            echo "Deploy $VERSION to $MILJO in prod-sbs"
            deployment-cli deploy create --cluster=prod-sbs --repository=${GITHUB_REPOSITORY} --team=digisos -r=nais.yaml --var version=${VERSION} --vars=nais/prod/default.json
          fi
        env:
          DEPLOYMENT_USERNAME: ${{ secrets.DEPLOYMENT_USERNAME }}
          DEPLOYMENT_PASSWORD: ${{ secrets.DEPLOYMENT_PASSWORD }}
